import * as React from 'react';

const countryListTrans = (props) =>{

    console.log(props)

return ( 

    <>
                                       
    {/* <option value="">{SiteTrans.becomepartner_country[currentPage.locale.id]}</option> */}
    {console.log("Checking this for language")}
    {console.log(props.lang)}
    {props.lang=="en_US" ?
    <>
        <option value="AFG">Afghanistan</option>
        <option value="ALB">Albania</option>
        <option value="DZA">Algeria</option>
        <option value="ASM">American Samoa</option>
        <option value="AND">Andorra</option>
        <option value="AGO">Angola</option>
        <option value="AIA">Anguilla</option>
        <option value="ATA">Antarctica</option>
        <option value="ATG">Antigua and Barbuda</option>
        <option value="ARG">Argentina</option>
        <option value="ARM">Armenia</option>
        <option value="ABW">Aruba</option>
        <option value="AUS">Australia</option>
        <option value="AUT">Austria</option>
        <option value="AZE">Azerbaijan</option>
        <option value="BHS">Bahamas</option>
        <option value="BHR">Bahrain</option>
        <option value="BGD">Bangladesh</option>
        <option value="BRB">Barbados</option>
        <option value="BLR">Belarus</option>
        <option value="BEL">Belgium</option>
        <option value="BLZ">Belize</option>
        <option value="BEN">Benin</option>
        <option value="BMU">Bermuda</option>
        <option value="BTN">Bhutan</option>
        <option value="BOL">Bolivia, Plurinational State of</option>
        <option value="BES">Bonaire, Sint Eustatius and Saba</option>
        <option value="BIH">Bosnia and Herzegovina</option>
        <option value="BWA">Botswana</option>
        <option value="BVT">Bouvet Island</option>
        <option value="BRA">Brazil</option>
        <option value="IOT">British Indian Ocean Territory</option>
        <option value="BRN">Brunei Darussalam</option>
        <option value="BGR">Bulgaria</option>
        <option value="BFA">Burkina Faso</option>
        <option value="BDI">Burundi</option>
        <option value="KHM">Cambodia</option>
        <option value="CMR">Cameroon</option>
        <option value="CAN">Canada</option>
        <option value="CPV">Cape Verde</option>
        <option value="CYM">Cayman Islands</option>
        <option value="CAF">Central African Republic</option>
        <option value="TCD">Chad</option>
        <option value="CHL">Chile</option>
        <option value="CHN">China</option>
        <option value="CXR">Christmas Island</option>
        <option value="CCK">Cocos (Keeling) Islands</option>
        <option value="COL">Colombia</option>
        <option value="COM">Comoros</option>
        <option value="COG">Congo</option>
        <option value="COD">Congo, the Democratic Republic of the</option>
        <option value="COK">Cook Islands</option>
        <option value="CRI">Costa Rica</option>
        <option value="CIV">Cote d'Ivoire</option>
        <option value="HRV">Croatia</option>
        <option value="CUB">Cuba</option>
        <option value="CUW">Curaçao</option>
        <option value="CYP">Cyprus</option>
        <option value="CZE">Czech Republic</option>
        <option value="DNK">Denmark</option>
        <option value="DJI">Djibouti</option>
        <option value="DMA">Dominica</option>
        <option value="DOM">Dominican Republic</option>
        <option value="ECU">Ecuador</option>
        <option value="EGY">Egypt</option>
        <option value="SLV">El Salvador</option>
        <option value="GNQ">Equatorial Guinea</option>
        <option value="ERI">Eritrea</option>
        <option value="EST">Estonia</option>
        <option value="ETH">Ethiopia</option>
        <option value="FLK">Falkland Islands (Malvinas)</option>
        <option value="FRO">Faroe Islands</option>
        <option value="FJI">Fiji</option>
        <option value="FIN">Finland</option>
        <option value="FRA">France</option>
        <option value="GUF">French Guiana</option>
        <option value="PYF">French Polynesia</option>
        <option value="ATF">French Southern Territories</option>
        <option value="GAB">Gabon</option>
        <option value="GMB">Gambia</option>
        <option value="GEO">Georgia</option>
        <option value="DEU">Germany</option>
        <option value="GHA">Ghana</option>
        <option value="GIB">Gibraltar</option>
        <option value="GRC">Greece</option>
        <option value="GRL">Greenland</option>
        <option value="GRD">Grenada</option>
        <option value="GLP">Guadeloupe</option>
        <option value="GUM">Guam</option>
        <option value="GTM">Guatemala</option>
        <option value="GGY">Guernsey</option>
        <option value="GIN">Guinea</option>
        <option value="GNB">Guinea-Bissau</option>
        <option value="GUY">Guyana</option>
        <option value="HTI">Haiti</option>
        <option value="HMD">Heard Island and McDonald Islands</option>
        <option value="VAT">Holy See (Vatican City State)</option>
        <option value="HND">Honduras</option>
        <option value="HKG">Hong Kong</option>
        <option value="HUN">Hungary</option>
        <option value="ISL">Iceland</option>
        <option value="IND">India</option>
        <option value="IDN">Indonesia</option>
        <option value="IRN">Iran, Islamic Republic of</option>
        <option value="IRQ">Iraq</option>
        <option value="IRL">Ireland</option>
        <option value="IMN">Isle of Man</option>
        <option value="ISR">Israel</option>
        <option value="ITA">Italy</option>
        <option value="JAM">Jamaica</option>
        <option value="JPN">Japan</option>
        <option value="JEY">Jersey</option>
        <option value="JOR">Jordan</option>
        <option value="KAZ">Kazakhstan</option>
        <option value="KEN">Kenya</option>
        <option value="KIR">Kiribati</option>
        <option value="PRK">Korea, Democratic People's Republic of</option>
        <option value="KOR">Korea, Republic of</option>
        <option value="KWT">Kuwait</option>
        <option value="KGZ">Kyrgyzstan</option>
        <option value="LAO">Lao People's Democratic Republic</option>
        <option value="LVA">Latvia</option>
        <option value="LBN">Lebanon</option>
        <option value="LSO">Lesotho</option>
        <option value="LBR">Liberia</option>
        <option value="LBY">Libya</option>
        <option value="LIE">Liechtenstein</option>
        <option value="LTU">Lithuania</option>
        <option value="LUX">Luxembourg</option>
        <option value="MAC">Macao</option>
        <option value="MKD">Macedonia, the Former Yugoslav Republic of</option>
        <option value="MDG">Madagascar</option>
        <option value="MWI">Malawi</option>
        <option value="MYS">Malaysia</option>
        <option value="MDV">Maldives</option>
        <option value="MLI">Mali</option>
        <option value="MLT">Malta</option>
        <option value="MHL">Marshall Islands</option>
        <option value="MTQ">Martinique</option>
        <option value="MRT">Mauritania</option>
        <option value="MUS">Mauritius</option>
        <option value="MYT">Mayotte</option>
        <option value="MEX">Mexico</option>
        <option value="FSM">Micronesia, Federated States of</option>
        <option value="MDA">Moldova, Republic of</option>
        <option value="MCO">Monaco</option>
        <option value="MNG">Mongolia</option>
        <option value="MNE">Montenegro</option>
        <option value="MSR">Montserrat</option>
        <option value="MAR">Morocco</option>
        <option value="MOZ">Mozambique</option>
        <option value="MMR">Myanmar</option>
        <option value="NAM">Namibia</option>
        <option value="NRU">Nauru</option>
        <option value="NPL">Nepal</option>
        <option value="NLD">Netherlands</option>
        <option value="NCL">New Caledonia</option>
        <option value="NZL">New Zealand</option>
        <option value="NIC">Nicaragua</option>
        <option value="NER">Niger</option>
        <option value="NGA">Nigeria</option>
        <option value="NIU">Niue</option>
        <option value="NFK">Norfolk Island</option>
        <option value="MNP">Northern Mariana Islands</option>
        <option value="NOR">Norway</option>
        <option value="OMN">Oman</option>
        <option value="PAK">Pakistan</option>
        <option value="PLW">Palau</option>
        <option value="PSE">Palestinian, State of</option>
        <option value="PAN">Panama</option>
        <option value="PNG">Papua New Guinea</option>
        <option value="PRY">Paraguay</option>
        <option value="PER">Peru</option>
        <option value="PHL">Philippines</option>
        <option value="PCN">Pitcairn</option>
        <option value="POL">Poland</option>
        <option value="PRT">Portugal</option>
        <option value="PRI">Puerto Rico</option>
        <option value="QAT">Qatar</option>
        <option value="ROU">Romania</option>
        <option value="RUS">Russian Federation</option>
        <option value="RWA">Rwanda</option>
        <option value="REU">Réunion</option>
        <option value="BLM">Saint Barthelemy</option>
        <option value="SHN">Saint Helena, Ascension and Tristan da Cunha</option>
        <option value="KNA">Saint Kitts and Nevis</option>
        <option value="LCA">Saint Lucia</option>
        <option value="MAF">Saint Martin (French Part)</option>
        <option value="SPM">Saint Pierre and Miquelon</option>
        <option value="VCT">Saint Vincent and the Grenadines</option>
        <option value="WSM">Samoa</option>
        <option value="SMR">San Marino</option>
        <option value="STP">Sao Tome and Principe</option>
        <option value="SAU">Saudi Arabia</option>
        <option value="SEN">Senegal</option>
        <option value="SRB">Serbia</option>
        <option value="SYC">Seychelles</option>
        <option value="SLE">Sierra Leone</option>
        <option value="SGP">Singapore</option>
        <option value="SXM">Sint Maarten (Dutch Part)</option>
        <option value="SVK">Slovakia</option>
        <option value="SVN">Slovenia</option>
        <option value="SLB">Solomon Islands</option>
        <option value="SOM">Somalia</option>
        <option value="ZAF">South Africa</option>
        <option value="SGS">South Georgia and the South Sandwich Islands</option>
        <option value="SSD">South Sudan</option>
        <option value="ESP">Spain</option>
        <option value="LKA">Sri Lanka</option>
        <option value="SDN">Sudan</option>
        <option value="SUR">Suriname</option>
        <option value="SJM">Svalbard and Jan Mayen</option>
        <option value="SWZ">Swaziland</option>
        <option value="SWE">Sweden</option>
        <option value="CHE">Switzerland</option>
        <option value="SYR">Syrian Arab Republic</option>
        <option value="TWN">Taiwan, Province of China</option>
        <option value="TJK">Tajikistan</option>
        <option value="TZA">Tanzania, United Republic of</option>
        <option value="THA">Thailand</option>
        <option value="TLS">Timor-Leste</option>
        <option value="TGO">Togo</option>
        <option value="TKL">Tokelau</option>
        <option value="TON">Tonga</option>
        <option value="TTO">Trinidad and Tobago</option>
        <option value="TUN">Tunisia</option>
        <option value="TUR">Turkey</option>
        <option value="TKM">Turkmenistan</option>
        <option value="TCA">Turks and Caicos Islands</option>
        <option value="TUV">Tuvalu</option>
        <option value="UGA">Uganda</option>
        <option value="UKR">Ukraine</option>
        <option value="ARE">United Arab Emirates</option>
        <option value="GBR">United Kingdom</option>
        <option value="USA">United States</option>
        <option value="UMI">United States Minor Outlying Islands</option>
        <option value="URY">Uruguay</option>
        <option value="UZB">Uzbekistan</option>
        <option value="VUT">Vanuatu</option>
        <option value="VEN">Venezuela, Bolivarian Republic of</option>
        <option value="VNM">Viet Nam</option>
        <option value="VGB">Virgin Islands, British</option>
        <option value="VIR">Virgin Islands, U.S.</option>
        <option value="WLF">Wallis and Futuna</option>
        <option value="ESH">Western Sahara</option>
        <option value="YEM">Yemen</option>
        <option value="ZMB">Zambia</option>
        <option value="ZWE">Zimbabwe</option>
        <option value="ALA">Åland Islands</option></>
:null}

{props.lang=="ar" ?
    <>
        <option value="ABW">آروبا</option>
        <option value="AZE">أذربيجان</option>
        <option value="ATF">أراض فرنسية جنوبية وأنتارتيكية</option>
        <option value="ARM">أرمينيا</option>
        <option value="ESP">أسبانيا</option>
        <option value="AUS">أستراليا</option>
        <option value="AFG">أفغانستان</option>
        <option value="ALB">ألبانيا</option>
        <option value="DEU">ألمانيا</option>
        <option value="ATG">أنتيغوا وباربودا</option>
        <option value="AGO">أنجولا</option>
        <option value="AIA">أنجويلا</option>
        <option value="AND">أندورا</option>
        <option value="URY">أورجواي</option>
        <option value="UZB">أوزبكستان</option>
        <option value="UGA">أوغندا</option>
        <option value="UKR">أوكرانيا</option>
        <option value="IRL">أيرلندا</option>
        <option value="ISL">أيسلندا</option>
        <option value="IOT">إقليم المحيط الهندي البريطاني</option>
        <option value="ETH">اثيوبيا</option>
        <option value="ERI">اريتريا</option>
        <option value="EST">استونيا</option>
        <option value="ISR">اسرائيل</option>
        <option value="ARG">الأرجنتين</option>
        <option value="JOR">الأردن</option>
        <option value="ECU">الاكوادور</option>
        <option value="ARE">الامارات العربية المتحدة</option>
        <option value="BHS">الباهاما</option>
        <option value="BHR">البحرين</option>
        <option value="BRA">البرازيل</option>
        <option value="PRT">البرتغال</option>
        <option value="BIH">البوسنة والهرسك</option>
        <option value="GAB">الجابون</option>
        <option value="MNE">الجبل الأسود</option>
        <option value="DZA">الجزائر</option>
        <option value="BES">الجزر الكاريبية الهولندية</option>
        <option value="DNK">الدانمرك</option>
        <option value="CPV">الرأس الأخضر</option>
        <option value="SAU">السعودية</option>
        <option value="SLV">السلفادور</option>
        <option value="SEN">السنغال</option>
        <option value="SDN">السودان</option>
        <option value="SWE">السويد</option>
        <option value="ESH">الصحراء الغربية</option>
        <option value="SOM">الصومال</option>
        <option value="CHN">الصين</option>
        <option value="IRQ">العراق</option>
        <option value="VAT">الفاتيكان</option>
        <option value="PHL">الفيلبين</option>
        <option value="ATA">القارة القطبية الجنوبية</option>
        <option value="CMR">الكاميرون</option>
        <option value="KWT">الكويت</option>
        <option value="HUN">المجر</option>
        <option value="MAR">المغرب</option>
        <option value="MEX">المكسيك</option>
        <option value="GBR">المملكة المتحدة</option>
        <option value="NOR">النرويج</option>
        <option value="AUT">النمسا</option>
        <option value="NER">النيجر</option>
        <option value="IND">الهند</option>
        <option value="USA">الولايات المتحدة</option>
        <option value="JPN">اليابان</option>
        <option value="YEM">اليمن</option>
        <option value="GRC">اليونان</option>
        <option value="IDN">اندونيسيا</option>
        <option value="IRN">ايران</option>
        <option value="ITA">ايطاليا</option>
        <option value="PNG">بابوا غينيا الجديدة</option>
        <option value="PRY">باراجواي</option>
        <option value="PAK">باكستان</option>
        <option value="PLW">بالاو</option>
        <option value="BWA">بتسوانا</option>
        <option value="PCN">بتكايرن</option>
        <option value="BRB">بربادوس</option>
        <option value="BMU">برمودا</option>
        <option value="BRN">بروناي</option>
        <option value="BEL">بلجيكا</option>
        <option value="BGR">بلغاريا</option>
        <option value="BLZ">بليز</option>
        <option value="BGD">بنجلاديش</option>
        <option value="PAN">بنما</option>
        <option value="BEN">بنين</option>
        <option value="BTN">بوتان</option>
        <option value="PRI">بورتوريكو</option>
        <option value="BFA">بوركينا فاسو</option>
        <option value="BDI">بوروندي</option>
        <option value="POL">بولندا</option>
        <option value="BOL">بوليفيا</option>
        <option value="PYF">بولينزيا الفرنسية</option>
        <option value="PER">بيرو</option>
        <option value="TZA">تانزانيا</option>
        <option value="THA">تايلند</option>
        <option value="TWN">تايوان</option>
        <option value="MAF">تجمع سان مارتين</option>
        <option value="TKM">تركمانستان</option>
        <option value="TUR">تركيا</option>
        <option value="TTO">ترينيداد وتوباغو</option>
        <option value="TCD">تشاد</option>
        <option value="TGO">توجو</option>
        <option value="TUV">توفالو</option>
        <option value="TKL">توكيلو</option>
        <option value="TON">تونجا</option>
        <option value="TUN">تونس</option>
        <option value="TLS">تيمور الشرقية</option>
        <option value="JAM">جامايكا</option>
        <option value="GIB">جبل طارق</option>
        <option value="GRD">جرينادا</option>
        <option value="GRL">جرينلاند</option>
        <option value="ALA">جزر أولان</option>
        <option value="VIR">جزر العذراء الأمريكية</option>
        <option value="VGB">جزر العذراء البريطانية</option>
        <option value="COM">جزر القمر</option>
        <option value="MDV">جزر المالديف</option>
        <option value="UMI">جزر الولايات المتحدة الصغيرة النائية</option>
        <option value="TCA">جزر توركس وكايكوس</option>
        <option value="SLB">جزر سليمان</option>
        <option value="FRO">جزر فارو</option>
        <option value="FLK">جزر فوكلاند</option>
        <option value="CYM">جزر كايمان</option>
        <option value="COK">جزر كوك</option>
        <option value="CCK">جزر كوكوس</option>
        <option value="MHL">جزر مارشال</option>
        <option value="MNP">جزر ماريانا الشمالية</option>
        <option value="BVT">جزيرة بوفيه</option>
        <option value="CXR">جزيرة عيد الميلاد</option>
        <option value="IMN">جزيرة مان</option>
        <option value="NFK">جزيرة نورفولك</option>
        <option value="HMD">جزيرة هيرد وجزر ماكدونالد</option>
        <option value="CAF">جمهورية أفريقيا الوسطى</option>
        <option value="CZE">جمهورية التشيك</option>
        <option value="DOM">جمهورية الدومينيكان</option>
        <option value="COG">جمهورية الكونغو</option>
        <option value="COD">جمهورية الكونغو الديمقراطية</option>
        <option value="ZAF">جنوب أفريقيا</option>
        <option value="SSD">جنوب السودان</option>
        <option value="GTM">جواتيمالا</option>
        <option value="GLP">جوادلوب</option>
        <option value="GUM">جوام</option>
        <option value="GEO">جورجيا</option>
        <option value="SGS">جورجيا الجنوبية وجزر ساندويتش الجنوبية</option>
        <option value="DJI">جيبوتي</option>
        <option value="JEY">جيرسي</option>
        <option value="GGY">جيرنزي</option>
        <option value="DMA">دومينيكا</option>
        <option value="RWA">رواندا</option>
        <option value="RUS">روسيا</option>
        <option value="BLR">روسيا البيضاء</option>
        <option value="ROU">رومانيا</option>
        <option value="REU">روينيون</option>
        <option value="ZMB">زامبيا</option>
        <option value="ZWE">زيمبابوي</option>
        <option value="CIV">ساحل العاج</option>
        <option value="WSM">ساموا</option>
        <option value="ASM">ساموا الأمريكية</option>
        <option value="BLM">سان بارتيلمي</option>
        <option value="SPM">سان بيير وميكلون</option>
        <option value="SMR">سان مارينو</option>
        <option value="VCT">سانت فينسنت والغرينادين</option>
        <option value="KNA">سانت كيتس ونيفيس</option>
        <option value="LCA">سانت لوسيا</option>
        <option value="SHN">سانت هيلينا وأسينشين وتريستان دا كونا</option>
        <option value="STP">ساو تومي وبرينسيب</option>
        <option value="LKA">سريلانكا</option>
        <option value="SJM">سفالبارد ويان ماين</option>
        <option value="SVK">سلوفاكيا</option>
        <option value="SVN">سلوفينيا</option>
        <option value="SGP">سنغافورة</option>
        <option value="SWZ">سوازيلاند</option>
        <option value="SYR">سوريا</option>
        <option value="SUR">سورينام</option>
        <option value="CHE">سويسرا</option>
        <option value="SLE">سيراليون</option>
        <option value="SYC">سيشل</option>
        <option value="SXM">سينت مارتن</option>
        <option value="CHL">شيلي</option>
        <option value="SRB">صربيا</option>
        <option value="TJK">طاجكستان</option>
        <option value="OMN">عمان</option>
        <option value="GMB">غامبيا</option>
        <option value="GHA">غانا</option>
        <option value="GUF">غويانا</option>
        <option value="GUY">غيانا</option>
        <option value="GIN">غينيا</option>
        <option value="GNQ">غينيا الاستوائية</option>
        <option value="GNB">غينيا بيساو</option>
        <option value="VUT">فانواتو</option>
        <option value="FRA">فرنسا</option>
        <option value="PSE">فلسطين</option>
        <option value="VEN">فنزويلا</option>
        <option value="FIN">فنلندا</option>
        <option value="VNM">فيتنام</option>
        <option value="FJI">فيجي</option>
        <option value="CYP">قبرص</option>
        <option value="KGZ">قرغيزستان</option>
        <option value="QAT">قطر</option>
        <option value="KAZ">كازاخستان</option>
        <option value="NCL">كاليدونيا الجديدة</option>
        <option value="HRV">كرواتيا</option>
        <option value="KHM">كمبوديا</option>
        <option value="CAN">كندا</option>
        <option value="CUB">كوبا</option>
        <option value="CUW">كوراساو</option>
        <option value="KOR">كوريا الجنوبية</option>
        <option value="PRK">كوريا الشمالية</option>
        <option value="CRI">كوستاريكا</option>
        <option value="COL">كولومبيا</option>
        <option value="KIR">كيريباتي</option>
        <option value="KEN">كينيا</option>
        <option value="LVA">لاتفيا</option>
        <option value="LAO">لاوس</option>
        <option value="LBN">لبنان</option>
        <option value="LUX">لوكسمبورج</option>
        <option value="LBY">ليبيا</option>
        <option value="LBR">ليبيريا</option>
        <option value="LTU">ليتوانيا</option>
        <option value="LIE">ليختنشتاين</option>
        <option value="LSO">ليسوتو</option>
        <option value="MTQ">مارتينيك</option>
        <option value="MAC">ماكاو</option>
        <option value="MLT">مالطا</option>
        <option value="MLI">مالي</option>
        <option value="MYS">ماليزيا</option>
        <option value="MYT">مايوت</option>
        <option value="MDG">مدغشقر</option>
        <option value="EGY">مصر</option>
        <option value="MKD">مقدونيا</option>
        <option value="MWI">ملاوي</option>
        <option value="MNG">منغوليا</option>
        <option value="MRT">موريتانيا</option>
        <option value="MUS">موريشيوس</option>
        <option value="MOZ">موزمبيق</option>
        <option value="MDA">مولدافيا</option>
        <option value="MCO">موناكو</option>
        <option value="MSR">مونتسرات</option>
        <option value="MMR">ميانمار</option>
        <option value="FSM">ميكرونيزيا</option>
        <option value="NAM">ناميبيا</option>
        <option value="NRU">نورو</option>
        <option value="NPL">نيبال</option>
        <option value="NGA">نيجيريا</option>
        <option value="NIC">نيكاراجوا</option>
        <option value="NZL">نيوزيلاندا</option>
        <option value="NIU">نيوي</option>
        <option value="HTI">هايتي</option>
        <option value="HND">هندوراس</option>
        <option value="NLD">هولندا</option>
        <option value="HKG">هونغ كونغ</option>
        <option value="WLF">والس وفوتونا</option>

    </>:null}

  {props.lang=="tr_TR" ?
    <>
        <option value="VIR">ABD Virgin Adaları</option>
        <option value="AFG">Afganistan</option>
        <option value="ALA">Aland Adaları</option>
        <option value="DEU">Almanya</option>
        <option value="USA">Amerika Birleşik Devletleri</option>
        <option value="UMI">Amerika Birleşik Devletleri Küçük Dış Adaları</option>
        <option value="ASM">Amerikan Samoası</option>
        <option value="AND">Andorra</option>
        <option value="AGO">Angola</option>
        <option value="AIA">Anguilla</option>
        <option value="ATA">Antarktika</option>
        <option value="ATG">Antigua ve Barbuda</option>
        <option value="ARG">Arjantin</option>
        <option value="ALB">Arnavutluk</option>
        <option value="ABW">Aruba</option>
        <option value="AUS">Avustralya</option>
        <option value="AUT">Avusturya</option>
        <option value="AZE">Azerbaycan</option>
        <option value="BHS">Bahamalar</option>
        <option value="BHR">Bahreyn</option>
        <option value="BGD">Bangladeş</option>
        <option value="BRB">Barbados</option>
        <option value="ESH">Batı Sahara</option>
        <option value="BLZ">Belize</option>
        <option value="BEL">Belçika</option>
        <option value="BEN">Benin</option>
        <option value="BMU">Bermuda</option>
        <option value="BLR">Beyaz Rusya</option>
        <option value="BTN">Bhutan</option>
        <option value="ARE">Birleşik Arap Emirlikleri</option>
        <option value="GBR">Birleşik Krallık</option>
        <option value="MMR">Birmanya</option>
        <option value="BOL">Bolivya</option>
        <option value="BES">Bonaire, Sint Eustatius ve Saba</option>
        <option value="BIH">Bosna Hersek</option>
        <option value="BWA">Botsvana</option>
        <option value="BVT">Bouvet Adası</option>
        <option value="BRA">Brezilya</option>
        <option value="BRN">Brunei</option>
        <option value="BGR">Bulgaristan</option>
        <option value="BFA">Burkina Faso</option>
        <option value="BDI">Burundi</option>
        <option value="CYM">Cayman Adaları</option>
        <option value="GIB">Cebelitarık</option>
        <option value="DZA">Cezayir</option>
        <option value="CXR">Christmas Adası</option>
        <option value="DJI">Cibuti</option>
        <option value="CCK">Cocos Adaları</option>
        <option value="COK">Cook Adaları</option>
        <option value="CUW">Curaçao</option>
        <option value="DNK">Danimarka</option>
        <option value="DOM">Dominik Cumhuriyeti</option>
        <option value="DMA">Dominika</option>
        <option value="TLS">Doğu Timor</option>
        <option value="ECU">Ekvador</option>
        <option value="GNQ">Ekvator Ginesi</option>
        <option value="SLV">El Salvador</option>
        <option value="IDN">Endonezya</option>
        <option value="ERI">Eritre</option>
        <option value="ARM">Ermenistan</option>
        <option value="EST">Estonya</option>
        <option value="ETH">Etiyopya</option>
        <option value="FLK">Falkland Adaları</option>
        <option value="FRO">Faroe Adaları</option>
        <option value="MAR">Fas</option>
        <option value="FJI">Fiji</option>
        <option value="CIV">Fildişi Sahili</option>
        <option value="PHL">Filipinler</option>
        <option value="PSE">Filistin Bölgesi</option>
        <option value="FIN">Finlandiya</option>
        <option value="FRA">Fransa</option>
        <option value="GUF">Fransız Guyanası</option>
        <option value="ATF">Fransız Güney Bölgeleri</option>
        <option value="PYF">Fransız Polinezyası</option>
        <option value="GAB">Gabon</option>
        <option value="GMB">Gambiya</option>
        <option value="GHA">Gana</option>
        <option value="GIN">Gine</option>
        <option value="GNB">Gine-Bissau</option>
        <option value="GRD">Granada</option>
        <option value="GRL">Grönland</option>
        <option value="GLP">Guadalupe</option>
        <option value="GUM">Guam</option>
        <option value="GTM">Guatemala</option>
        <option value="GGY">Guernsey</option>
        <option value="GUY">Guyana</option>
        <option value="ZAF">Güney Afrika</option>
        <option value="SGS">Güney Georgia ve Güney Sandwich Adaları</option>
        <option value="KOR">Güney Kore</option>
        <option value="CYP">Güney Kıbrıs Rum Kesimi</option>
        <option value="SSD">Güney Sudan</option>
        <option value="GEO">Gürcistan</option>
        <option value="HTI">Haiti</option>
        <option value="HMD">Heard Adası ve McDonald Adaları</option>
        <option value="IND">Hindistan</option>
        <option value="IOT">Hint Okyanusu İngiliz Bölgesi</option>
        <option value="NLD">Hollanda</option>
        <option value="HND">Honduras</option>
        <option value="HKG">Hong Kong SAR - Çin</option>
        <option value="HRV">Hırvatistan</option>
        <option value="IRQ">Irak</option>
        <option value="JAM">Jamaika</option>
        <option value="JPN">Japonya</option>
        <option value="JEY">Jersey</option>
        <option value="KHM">Kamboçya</option>
        <option value="CMR">Kamerun</option>
        <option value="CAN">Kanada</option>
        <option value="MNE">Karadağ</option>
        <option value="QAT">Katar</option>
        <option value="KAZ">Kazakistan</option>
        <option value="KEN">Kenya</option>
        <option value="KIR">Kiribati</option>
        <option value="COL">Kolombiya</option>
        <option value="COM">Komorlar</option>
        <option value="COG">Kongo - Brazavil</option>
        <option value="COD">Kongo - Kinşasa</option>
        <option value="CRI">Kosta Rika</option>
        <option value="KWT">Kuveyt</option>
        <option value="PRK">Kuzey Kore</option>
        <option value="MNP">Kuzey Mariana Adaları</option>
        <option value="CUB">Küba</option>
        <option value="KGZ">Kırgızistan</option>
        <option value="LAO">Laos</option>
        <option value="LSO">Lesoto</option>
        <option value="LVA">Letonya</option>
        <option value="LBR">Liberya</option>
        <option value="LBY">Libya</option>
        <option value="LIE">Liechtenstein</option>
        <option value="LTU">Litvanya</option>
        <option value="LBN">Lübnan</option>
        <option value="LUX">Lüksemburg</option>
        <option value="HUN">Macaristan</option>
        <option value="MDG">Madagaskar</option>
        <option value="MAC">Makao S.A.R. Çin</option>
        <option value="MKD">Makedonya</option>
        <option value="MWI">Malavi</option>
        <option value="MDV">Maldivler</option>
        <option value="MYS">Malezya</option>
        <option value="MLI">Mali</option>
        <option value="MLT">Malta</option>
        <option value="IMN">Man Adası</option>
        <option value="MHL">Marshall Adaları</option>
        <option value="MTQ">Martinik</option>
        <option value="MUS">Mauritius</option>
        <option value="MYT">Mayotte</option>
        <option value="MEX">Meksika</option>
        <option value="FSM">Mikronezya Federal Eyaletleri</option>
        <option value="MDA">Moldovya</option>
        <option value="MCO">Monako</option>
        <option value="MSR">Montserrat</option>
        <option value="MRT">Moritanya</option>
        <option value="MOZ">Mozambik</option>
        <option value="MNG">Moğolistan</option>
        <option value="EGY">Mısır</option>
        <option value="NAM">Namibya</option>
        <option value="NRU">Nauru</option>
        <option value="NPL">Nepal</option>
        <option value="NER">Nijer</option>
        <option value="NGA">Nijerya</option>
        <option value="NIC">Nikaragua</option>
        <option value="NIU">Niue</option>
        <option value="NFK">Norfolk Adası</option>
        <option value="NOR">Norveç</option>
        <option value="CAF">Orta Afrika Cumhuriyeti</option>
        <option value="PAK">Pakistan</option>
        <option value="PLW">Palau</option>
        <option value="PAN">Panama</option>
        <option value="PNG">Papua Yeni Gine</option>
        <option value="PRY">Paraguay</option>
        <option value="PER">Peru</option>
        <option value="PCN">Pitcairn</option>
        <option value="POL">Polonya</option>
        <option value="PRT">Portekiz</option>
        <option value="PRI">Porto Riko</option>
        <option value="REU">Reunion</option>
        <option value="ROU">Romanya</option>
        <option value="RWA">Ruanda</option>
        <option value="RUS">Rusya Federasyonu</option>
        <option value="BLM">Saint Barthelemy</option>
        <option value="SHN">Saint Helena</option>
        <option value="KNA">Saint Kitts ve Nevis</option>
        <option value="LCA">Saint Lucia</option>
        <option value="MAF">Saint Martin</option>
        <option value="SPM">Saint Pierre ve Miquelon</option>
        <option value="VCT">Saint Vincent ve Grenadinler</option>
        <option value="WSM">Samoa</option>
        <option value="SMR">San Marino</option>
        <option value="STP">Sao Tome ve Principe</option>
        <option value="SEN">Senegal</option>
        <option value="SYC">Seyşel Adaları</option>
        <option value="SLE">Sierra Leone</option>
        <option value="SGP">Singapur</option>
        <option value="SXM">Sint Maarten (Hollanda)</option>
        <option value="SVK">Slovakya</option>
        <option value="SVN">Slovenya</option>
        <option value="SLB">Solomon Adaları</option>
        <option value="SOM">Somali</option>
        <option value="LKA">Sri Lanka</option>
        <option value="SDN">Sudan</option>
        <option value="SUR">Surinam</option>
        <option value="SYR">Suriye</option>
        <option value="SAU">Suudi Arabistan</option>
        <option value="SJM">Svalbard ve Jan Mayen</option>
        <option value="SWZ">Svaziland</option>
        <option value="SRB">Sırbistan</option>
        <option value="TJK">Tacikistan</option>
        <option value="TZA">Tanzanya</option>
        <option value="THA">Tayland</option>
        <option value="TWN">Tayvan</option>
        <option value="TGO">Togo</option>
        <option value="TKL">Tokelau</option>
        <option value="TON">Tonga</option>
        <option value="TTO">Trinidad ve Tobago</option>
        <option value="TUN">Tunus</option>
        <option value="TCA">Turks ve Caicos Adaları</option>
        <option value="TUV">Tuvalu</option>
        <option value="TUR">Türkiye</option>
        <option value="TKM">Türkmenistan</option>
        <option value="UGA">Uganda</option>
        <option value="UKR">Ukrayna</option>
        <option value="OMN">Umman</option>
        <option value="URY">Uruguay</option>
        <option value="VUT">Vanuatu</option>
        <option value="VAT">Vatikan</option>
        <option value="VEN">Venezuela</option>
        <option value="VNM">Vietnam</option>
        <option value="WLF">Wallis ve Futuna</option>
        <option value="YEM">Yemen</option>
        <option value="NCL">Yeni Kaledonya</option>
        <option value="NZL">Yeni Zelanda</option>
        <option value="CPV">Yeşilburun</option>
        <option value="GRC">Yunanistan</option>
        <option value="ZMB">Zambiya</option>
        <option value="ZWE">Zimbabve</option>
        <option value="TCD">Çad</option>
        <option value="CZE">Çek Cumhuriyeti</option>
        <option value="CHN">Çin</option>
        <option value="UZB">Özbekistan</option>
        <option value="JOR">Ürdün</option>
        <option value="VGB">İngiliz Virgin Adaları</option>
        <option value="IRN">İran</option>
        <option value="IRL">İrlanda</option>
        <option value="ESP">İspanya</option>
        <option value="ISR">İsrail</option>
        <option value="SWE">İsveç</option>
        <option value="CHE">İsviçre</option>
        <option value="ITA">İtalya</option>
        <option value="ISL">İzlanda</option>
        <option value="CHL">Şili</option>
    </>: null}                                                
    </>
)}

export default countryListTrans